syntax = "proto3";

package github.com.kheeva.mini_messenger.auth;

import "buf/validate/validate.proto";
import "google/api/field_behavior.proto";
import "protoc-gen-openapiv2/options/annotations.proto";

option go_package = "pkg/api/auth;auth";

// Запрос AuthService.Register
message RegisterRequest {
  // email - уникальный атрибут пользователя
  string email = 1;
  // инварианты: длина больше 12 символов, как комбинация букв разного регистра и цифр
  string password = 2;
}

// Ответ AuthService.Register
message RegisterResponse {
  // user_id - уникальный идентификатор пользователя
  string user_id = 1;
}

// Запрос AuthService.Login
message LoginRequest {
  // email пользователя для аутентификации
  string email = 1;
  // password польщователя для аутентификации
  string password = 2;
}

// Ответ AuthService.Login
message LoginResponse {
  // access_token пользователя для последующей авториации
  string access_token = 1;
  // refresh_token пользователя для обновления access_token
  string refresh_token = 2;
  // user_id пользователя
  string user_id = 3;
}

// Запрос AuthService.Refresh
message RefreshRequest {
  // refresh_token пользователя
  string refresh_token = 1;
}

// Ответ AuthService.Refresh
message RefreshResponse {
  // access_token пользователя для последующей авториации
  string access_token = 1;
  // refresh_token пользователя для обновления access_token
  string refresh_token = 2;
  // user_id пользователя
  string user_id = 3;
}
