syntax = "proto3";

package github.com.kheeva.mini_messenger.auth;

import "auth/message.proto";

option go_package = "pkg/api/auth;auth";

// Сервис Регистрации и аутентификации пользователей в системе
service AuthService {
  // Регистрирует пользователя, по уникальному email
  rpc Register(RegisterRequest) returns (RegisterResponse) {}
  // Аутентифицирует пользователя и выдает ему авторизационный токен JWT
  rpc Login(LoginRequest) returns (LoginResponse) {}
  // Обновляет токен пользователя
  rpc Refresh(RefreshRequest) returns (RefreshResponse) {}
}
