// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: api/v1/user_service.proto

package user

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_v1_user_service_proto protoreflect.FileDescriptor

const file_api_v1_user_service_proto_rawDesc = "" +
	"\n" +
	"\x19api/v1/user_service.proto\x12%github.com.kheeva.mini_messenger.user\x1a\x1aapi/v1/user_messages.proto\x1a\x1cgoogle/api/annotations.proto2\xb4\a\n" +
	"\vUserService\x12\xb0\x01\n" +
	"\rCreateProfile\x12;.github.com.kheeva.mini_messenger.user.CreateProfileRequest\x1a<.github.com.kheeva.mini_messenger.user.CreateProfileResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/api/user/v1/user_profile\x12\xb0\x01\n" +
	"\rUpdateProfile\x12;.github.com.kheeva.mini_messenger.user.UpdateProfileRequest\x1a<.github.com.kheeva.mini_messenger.user.UpdateProfileResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\x1a\x19/api/user/v1/user_profile\x12\xb5\x01\n" +
	"\x0eGetProfileByID\x12<.github.com.kheeva.mini_messenger.user.GetProfileByIDRequest\x1a=.github.com.kheeva.mini_messenger.user.GetProfileByIDResponse\"&\x82\xd3\xe4\x93\x02 \x12\x1e/api/user/v1/user_profile/{id}\x12\xcd\x01\n" +
	"\x14GetProfileByNickname\x12B.github.com.kheeva.mini_messenger.user.GetProfileByNicknameRequest\x1aC.github.com.kheeva.mini_messenger.user.GetProfileByNicknameResponse\",\x82\xd3\xe4\x93\x02&\x12$/api/user/v1/user_profile/{nickname}\x12\xb6\x01\n" +
	"\x10SearchByNickname\x12>.github.com.kheeva.mini_messenger.user.SearchByNicknameRequest\x1a?.github.com.kheeva.mini_messenger.user.SearchByNicknameResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/api/user/v1/user_profileB\x82\x02\n" +
	")com.github.com.kheeva.mini_messenger.userB\x10UserServiceProtoP\x01Z\ruser/pkg;user\xa2\x02\x05GCKMU\xaa\x02$Github.Com.Kheeva.MiniMessenger.User\xca\x02$Github\\Com\\Kheeva\\MiniMessenger\\User\xe2\x020Github\\Com\\Kheeva\\MiniMessenger\\User\\GPBMetadata\xea\x02(Github::Com::Kheeva::MiniMessenger::Userb\x06proto3"

var file_api_v1_user_service_proto_goTypes = []any{
	(*CreateProfileRequest)(nil),         // 0: github.com.kheeva.mini_messenger.user.CreateProfileRequest
	(*UpdateProfileRequest)(nil),         // 1: github.com.kheeva.mini_messenger.user.UpdateProfileRequest
	(*GetProfileByIDRequest)(nil),        // 2: github.com.kheeva.mini_messenger.user.GetProfileByIDRequest
	(*GetProfileByNicknameRequest)(nil),  // 3: github.com.kheeva.mini_messenger.user.GetProfileByNicknameRequest
	(*SearchByNicknameRequest)(nil),      // 4: github.com.kheeva.mini_messenger.user.SearchByNicknameRequest
	(*CreateProfileResponse)(nil),        // 5: github.com.kheeva.mini_messenger.user.CreateProfileResponse
	(*UpdateProfileResponse)(nil),        // 6: github.com.kheeva.mini_messenger.user.UpdateProfileResponse
	(*GetProfileByIDResponse)(nil),       // 7: github.com.kheeva.mini_messenger.user.GetProfileByIDResponse
	(*GetProfileByNicknameResponse)(nil), // 8: github.com.kheeva.mini_messenger.user.GetProfileByNicknameResponse
	(*SearchByNicknameResponse)(nil),     // 9: github.com.kheeva.mini_messenger.user.SearchByNicknameResponse
}
var file_api_v1_user_service_proto_depIdxs = []int32{
	0, // 0: github.com.kheeva.mini_messenger.user.UserService.CreateProfile:input_type -> github.com.kheeva.mini_messenger.user.CreateProfileRequest
	1, // 1: github.com.kheeva.mini_messenger.user.UserService.UpdateProfile:input_type -> github.com.kheeva.mini_messenger.user.UpdateProfileRequest
	2, // 2: github.com.kheeva.mini_messenger.user.UserService.GetProfileByID:input_type -> github.com.kheeva.mini_messenger.user.GetProfileByIDRequest
	3, // 3: github.com.kheeva.mini_messenger.user.UserService.GetProfileByNickname:input_type -> github.com.kheeva.mini_messenger.user.GetProfileByNicknameRequest
	4, // 4: github.com.kheeva.mini_messenger.user.UserService.SearchByNickname:input_type -> github.com.kheeva.mini_messenger.user.SearchByNicknameRequest
	5, // 5: github.com.kheeva.mini_messenger.user.UserService.CreateProfile:output_type -> github.com.kheeva.mini_messenger.user.CreateProfileResponse
	6, // 6: github.com.kheeva.mini_messenger.user.UserService.UpdateProfile:output_type -> github.com.kheeva.mini_messenger.user.UpdateProfileResponse
	7, // 7: github.com.kheeva.mini_messenger.user.UserService.GetProfileByID:output_type -> github.com.kheeva.mini_messenger.user.GetProfileByIDResponse
	8, // 8: github.com.kheeva.mini_messenger.user.UserService.GetProfileByNickname:output_type -> github.com.kheeva.mini_messenger.user.GetProfileByNicknameResponse
	9, // 9: github.com.kheeva.mini_messenger.user.UserService.SearchByNickname:output_type -> github.com.kheeva.mini_messenger.user.SearchByNicknameResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_v1_user_service_proto_init() }
func file_api_v1_user_service_proto_init() {
	if File_api_v1_user_service_proto != nil {
		return
	}
	file_api_v1_user_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_user_service_proto_rawDesc), len(file_api_v1_user_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_user_service_proto_goTypes,
		DependencyIndexes: file_api_v1_user_service_proto_depIdxs,
	}.Build()
	File_api_v1_user_service_proto = out.File
	file_api_v1_user_service_proto_goTypes = nil
	file_api_v1_user_service_proto_depIdxs = nil
}
