version: "3.9"

services:
  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    image: mini_messenger-auth:local
    container_name: mini_messenger-auth
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment: []
    healthcheck:
      test: ["CMD", "/grpc_health_probe", "-addr=localhost:8000"]
      interval: 10s
      timeout: 3s
      retries: 3

networks:
  default:
    name: mini_messenger
