// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: api/v1/auth_messages.proto

package auth

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Запрос AuthService.Register
type RegisterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// email - уникальный атрибут пользователя
	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	// password - пароль пользователя. инварианты: длина больше 12 символов, как комбинация букв разного регистра и цифр
	Password      string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_api_v1_auth_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_auth_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_auth_messages_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// Ответ AuthService.Register
type RegisterResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// user_id - уникальный идентификатор пользователя
	UserId        string `protobuf:"bytes,1,opt,name=user_id,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_api_v1_auth_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_auth_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_auth_messages_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Запрос AuthService.Login
type LoginRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// email пользователя для аутентификации
	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	// password польщователя для аутентификации
	Password      string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_api_v1_auth_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_auth_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_auth_messages_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// Ответ AuthService.Login
type LoginResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// access_token пользователя для последующей авториации
	AccessToken string `protobuf:"bytes,1,opt,name=access_token,proto3" json:"access_token,omitempty"`
	// refresh_token пользователя для обновления access_token
	RefreshToken string `protobuf:"bytes,2,opt,name=refresh_token,proto3" json:"refresh_token,omitempty"`
	// user_id пользователя
	UserId        string `protobuf:"bytes,3,opt,name=user_id,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_api_v1_auth_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_auth_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_auth_messages_proto_rawDescGZIP(), []int{3}
}

func (x *LoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *LoginResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Запрос AuthService.Refresh
type RefreshRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// refresh_token пользователя
	RefreshToken  string `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshRequest) Reset() {
	*x = RefreshRequest{}
	mi := &file_api_v1_auth_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshRequest) ProtoMessage() {}

func (x *RefreshRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_auth_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshRequest.ProtoReflect.Descriptor instead.
func (*RefreshRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_auth_messages_proto_rawDescGZIP(), []int{4}
}

func (x *RefreshRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

// Ответ AuthService.Refresh
type RefreshResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// access_token пользователя для последующей авториации
	AccessToken string `protobuf:"bytes,1,opt,name=access_token,proto3" json:"access_token,omitempty"`
	// refresh_token пользователя для обновления access_token
	RefreshToken string `protobuf:"bytes,2,opt,name=refresh_token,proto3" json:"refresh_token,omitempty"`
	// user_id пользователя
	UserId        string `protobuf:"bytes,3,opt,name=user_id,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshResponse) Reset() {
	*x = RefreshResponse{}
	mi := &file_api_v1_auth_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshResponse) ProtoMessage() {}

func (x *RefreshResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_auth_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshResponse.ProtoReflect.Descriptor instead.
func (*RefreshResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_auth_messages_proto_rawDescGZIP(), []int{5}
}

func (x *RefreshResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RefreshResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *RefreshResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

var File_api_v1_auth_messages_proto protoreflect.FileDescriptor

const file_api_v1_auth_messages_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/v1/auth_messages.proto\x12%github.com.kheeva.mini_messenger.auth\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xe8\x01\n" +
	"\x0fRegisterRequest\x12\x1d\n" +
	"\x05email\x18\x01 \x01(\tB\a\xbaH\x04r\x02`\x01R\x05email\x12\xb5\x01\n" +
	"\bpassword\x18\x02 \x01(\tB\x98\x01\xbaH\x94\x01\xba\x01\x8c\x01\n" +
	"\x11password_strength\x12.must contain lowercase, uppercase, and a digit\x1aGthis.matches(\"[a-z]\") && this.matches(\"[A-Z]\") && this.matches(\"[0-9]\")r\x02\x10\fR\bpassword\",\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\auser_id\x18\x01 \x01(\tR\auser_id\"I\n" +
	"\fLoginRequest\x12\x1d\n" +
	"\x05email\x18\x01 \x01(\tB\a\xbaH\x04r\x02`\x01R\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"s\n" +
	"\rLoginResponse\x12\"\n" +
	"\faccess_token\x18\x01 \x01(\tR\faccess_token\x12$\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\rrefresh_token\x12\x18\n" +
	"\auser_id\x18\x03 \x01(\tR\auser_id\">\n" +
	"\x0eRefreshRequest\x12,\n" +
	"\rrefresh_token\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\frefreshToken\"u\n" +
	"\x0fRefreshResponse\x12\"\n" +
	"\faccess_token\x18\x01 \x01(\tR\faccess_token\x12$\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\rrefresh_token\x12\x18\n" +
	"\auser_id\x18\x03 \x01(\tR\auser_idB\x83\x02\n" +
	")com.github.com.kheeva.mini_messenger.authB\x11AuthMessagesProtoP\x01Z\rauth/pkg;auth\xa2\x02\x05GCKMA\xaa\x02$Github.Com.Kheeva.MiniMessenger.Auth\xca\x02$Github\\Com\\Kheeva\\MiniMessenger\\Auth\xe2\x020Github\\Com\\Kheeva\\MiniMessenger\\Auth\\GPBMetadata\xea\x02(Github::Com::Kheeva::MiniMessenger::Authb\x06proto3"

var (
	file_api_v1_auth_messages_proto_rawDescOnce sync.Once
	file_api_v1_auth_messages_proto_rawDescData []byte
)

func file_api_v1_auth_messages_proto_rawDescGZIP() []byte {
	file_api_v1_auth_messages_proto_rawDescOnce.Do(func() {
		file_api_v1_auth_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_auth_messages_proto_rawDesc), len(file_api_v1_auth_messages_proto_rawDesc)))
	})
	return file_api_v1_auth_messages_proto_rawDescData
}

var file_api_v1_auth_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_v1_auth_messages_proto_goTypes = []any{
	(*RegisterRequest)(nil),  // 0: github.com.kheeva.mini_messenger.auth.RegisterRequest
	(*RegisterResponse)(nil), // 1: github.com.kheeva.mini_messenger.auth.RegisterResponse
	(*LoginRequest)(nil),     // 2: github.com.kheeva.mini_messenger.auth.LoginRequest
	(*LoginResponse)(nil),    // 3: github.com.kheeva.mini_messenger.auth.LoginResponse
	(*RefreshRequest)(nil),   // 4: github.com.kheeva.mini_messenger.auth.RefreshRequest
	(*RefreshResponse)(nil),  // 5: github.com.kheeva.mini_messenger.auth.RefreshResponse
}
var file_api_v1_auth_messages_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_v1_auth_messages_proto_init() }
func file_api_v1_auth_messages_proto_init() {
	if File_api_v1_auth_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_auth_messages_proto_rawDesc), len(file_api_v1_auth_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_v1_auth_messages_proto_goTypes,
		DependencyIndexes: file_api_v1_auth_messages_proto_depIdxs,
		MessageInfos:      file_api_v1_auth_messages_proto_msgTypes,
	}.Build()
	File_api_v1_auth_messages_proto = out.File
	file_api_v1_auth_messages_proto_goTypes = nil
	file_api_v1_auth_messages_proto_depIdxs = nil
}
