// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: api/service.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_service_proto protoreflect.FileDescriptor

const file_api_service_proto_rawDesc = "" +
	"\n" +
	"\x11api/service.proto\x12%github.com.kheeva.mini_messenger.auth\x1a\x11api/message.proto2\xfe\x02\n" +
	"\vAuthService\x12}\n" +
	"\bRegister\x126.github.com.kheeva.mini_messenger.auth.RegisterRequest\x1a7.github.com.kheeva.mini_messenger.auth.RegisterResponse\"\x00\x12t\n" +
	"\x05Login\x123.github.com.kheeva.mini_messenger.auth.LoginRequest\x1a4.github.com.kheeva.mini_messenger.auth.LoginResponse\"\x00\x12z\n" +
	"\aRefresh\x125.github.com.kheeva.mini_messenger.auth.RefreshRequest\x1a6.github.com.kheeva.mini_messenger.auth.RefreshResponse\"\x00B\xfe\x01\n" +
	")com.github.com.kheeva.mini_messenger.authB\fServiceProtoP\x01Z\rauth/pkg;auth\xa2\x02\x05GCKMA\xaa\x02$Github.Com.Kheeva.MiniMessenger.Auth\xca\x02$Github\\Com\\Kheeva\\MiniMessenger\\Auth\xe2\x020Github\\Com\\Kheeva\\MiniMessenger\\Auth\\GPBMetadata\xea\x02(Github::Com::Kheeva::MiniMessenger::Authb\x06proto3"

var file_api_service_proto_goTypes = []any{
	(*RegisterRequest)(nil),  // 0: github.com.kheeva.mini_messenger.auth.RegisterRequest
	(*LoginRequest)(nil),     // 1: github.com.kheeva.mini_messenger.auth.LoginRequest
	(*RefreshRequest)(nil),   // 2: github.com.kheeva.mini_messenger.auth.RefreshRequest
	(*RegisterResponse)(nil), // 3: github.com.kheeva.mini_messenger.auth.RegisterResponse
	(*LoginResponse)(nil),    // 4: github.com.kheeva.mini_messenger.auth.LoginResponse
	(*RefreshResponse)(nil),  // 5: github.com.kheeva.mini_messenger.auth.RefreshResponse
}
var file_api_service_proto_depIdxs = []int32{
	0, // 0: github.com.kheeva.mini_messenger.auth.AuthService.Register:input_type -> github.com.kheeva.mini_messenger.auth.RegisterRequest
	1, // 1: github.com.kheeva.mini_messenger.auth.AuthService.Login:input_type -> github.com.kheeva.mini_messenger.auth.LoginRequest
	2, // 2: github.com.kheeva.mini_messenger.auth.AuthService.Refresh:input_type -> github.com.kheeva.mini_messenger.auth.RefreshRequest
	3, // 3: github.com.kheeva.mini_messenger.auth.AuthService.Register:output_type -> github.com.kheeva.mini_messenger.auth.RegisterResponse
	4, // 4: github.com.kheeva.mini_messenger.auth.AuthService.Login:output_type -> github.com.kheeva.mini_messenger.auth.LoginResponse
	5, // 5: github.com.kheeva.mini_messenger.auth.AuthService.Refresh:output_type -> github.com.kheeva.mini_messenger.auth.RefreshResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_service_proto_init() }
func file_api_service_proto_init() {
	if File_api_service_proto != nil {
		return
	}
	file_api_message_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_service_proto_rawDesc), len(file_api_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_service_proto_goTypes,
		DependencyIndexes: file_api_service_proto_depIdxs,
	}.Build()
	File_api_service_proto = out.File
	file_api_service_proto_goTypes = nil
	file_api_service_proto_depIdxs = nil
}
