syntax = "proto3";

package github.com.kheeva.mini_messenger.user;

import "buf/validate/validate.proto";
import "google/api/field_behavior.proto";
import "protoc-gen-openapiv2/options/annotations.proto";

option go_package = "user/pkg;user";

// Запрос на создание пользователя
message CreateProfileRequest {
  // Id пользователя
  string user_id = 1 [(buf.validate.field).string.min_len = 1];
  // Псевдоним пользователя
  string nickname = 2 [(buf.validate.field).string.pattern = "^[a-z0-9_]{3,20}$"];
  // Дополнительная информация пользователя
  optional string bio = 3;
  // Ссылка на изображения аватара пользователя
  optional string avatar_url = 4 [(buf.validate.field).string.uri = true];
}

// Ответ на создание пользвователя
message CreateProfileResponse {
  // Id пользователя
  string user_id = 1;
  // Псевдоним пользователя
  string nickname = 2;
  // Дополнительная информация пользователя
  optional string bio = 3;
  // Ссылка на изображения аватара пользователя
  optional string avatar_url = 4;
}

// Запрос на обновление пользователя
message UpdateProfileRequest {
  // Id пользователя
  string user_id = 1 [(buf.validate.field).string.min_len = 1];
  // Псевдоним пользователя
  string nickname = 2 [(buf.validate.field).string.pattern = "^[a-z0-9_]{3,20}$"];
  // Дополнительная информация пользователя
  optional string bio = 3;
  // Ссылка на изображения аватара пользователя
  optional string avatar_url = 4 [(buf.validate.field).string.uri = true];
}

// Ответ на обновление пользователя
message UpdateProfileResponse {
  // Id пользователя
  string user_id = 1;
  // Псевдоним пользователя
  string nickname = 2;
  // Дополнительная информация пользователя
  optional string bio = 3;
  // Ссылка на изображения аватара пользователя
  optional string avatar_url = 4;
}

// Запрос пользователя по id
message GetProfileByIDRequest {
  string id = 1 [(buf.validate.field).string.min_len = 1];
}

// Ответ на запрос пользователя по id
message GetProfileByIDResponse {
  // Id пользователя
  string user_id = 1;
  // Псевдоним пользователя
  string nickname = 2;
  // Дополнительная информация пользователя
  optional string bio = 3;
  // Ссылка на изображения аватара пользователя
  optional string avatar_url = 4;
}

// Запрос пользователя по nickname
message GetProfileByNicknameRequest {
  string nickname = 1 [(buf.validate.field).string.pattern = "^[a-z0-9_]{3,20}$"];
}

// Ответ на запрос пользователя по nickname
message GetProfileByNicknameResponse {
  // Id пользователя
  string user_id = 1;
  // Псевдоним пользователя
  string nickname = 2;
  // Дополнительная информация пользователя
  optional string bio = 3;
  // Ссылка на изображения аватара пользователя
  optional string avatar_url = 4;
}

// Поиск пользователя по nickname
message SearchByNicknameRequest {
  // Поисковая строка
  string query = 1 [(buf.validate.field).string.min_len = 1];
  // Лимит вывода
  optional uint32 limit = 2 [(buf.validate.field).uint32.lte = 100];
}

// UserProfile
message UserProfile {
  // Id пользователя
  string user_id = 1;
  // Псевдоним пользователя
  string nickname = 2;
  // Дополнительная информация пользователя
  optional string bio = 3;
  // Ссылка на изображения аватара пользователя
  optional string avatar_url = 4;
}

// Ответ на поиск пользователя
message SearchByNicknameResponse {
  repeated UserProfile results = 1;
}
