// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: api/v1/social_messages.proto

package social

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Запрос на добавление в список друзей
type SendFriendRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Id пользователя
	UserId        string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendFriendRequest) Reset() {
	*x = SendFriendRequest{}
	mi := &file_api_v1_social_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendFriendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFriendRequest) ProtoMessage() {}

func (x *SendFriendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_social_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFriendRequest.ProtoReflect.Descriptor instead.
func (*SendFriendRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_social_messages_proto_rawDescGZIP(), []int{0}
}

func (x *SendFriendRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Ответ на добавление в список друзей
type SendFriendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendFriendResponse) Reset() {
	*x = SendFriendResponse{}
	mi := &file_api_v1_social_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendFriendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFriendResponse) ProtoMessage() {}

func (x *SendFriendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_social_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFriendResponse.ProtoReflect.Descriptor instead.
func (*SendFriendResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_social_messages_proto_rawDescGZIP(), []int{1}
}

func (x *SendFriendResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SendFriendResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// Запрос на получение списка запросов к пользователю
type ListRequestsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequestsRequest) Reset() {
	*x = ListRequestsRequest{}
	mi := &file_api_v1_social_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequestsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequestsRequest) ProtoMessage() {}

func (x *ListRequestsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_social_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequestsRequest.ProtoReflect.Descriptor instead.
func (*ListRequestsRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_social_messages_proto_rawDescGZIP(), []int{2}
}

func (x *ListRequestsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Данные запроса на добавление в друзья
type FriendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendRequest) Reset() {
	*x = FriendRequest{}
	mi := &file_api_v1_social_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendRequest) ProtoMessage() {}

func (x *FriendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_social_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendRequest.ProtoReflect.Descriptor instead.
func (*FriendRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_social_messages_proto_rawDescGZIP(), []int{3}
}

func (x *FriendRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *FriendRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// Ответ на получение списка запросов к пользователю
type ListRequestsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*FriendRequest       `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequestsResponse) Reset() {
	*x = ListRequestsResponse{}
	mi := &file_api_v1_social_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequestsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequestsResponse) ProtoMessage() {}

func (x *ListRequestsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_social_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequestsResponse.ProtoReflect.Descriptor instead.
func (*ListRequestsResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_social_messages_proto_rawDescGZIP(), []int{4}
}

func (x *ListRequestsResponse) GetRequests() []*FriendRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

// Запрос на принятие запроса на добавление в друзья
type AcceptFriendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptFriendRequest) Reset() {
	*x = AcceptFriendRequest{}
	mi := &file_api_v1_social_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptFriendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptFriendRequest) ProtoMessage() {}

func (x *AcceptFriendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_social_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptFriendRequest.ProtoReflect.Descriptor instead.
func (*AcceptFriendRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_social_messages_proto_rawDescGZIP(), []int{5}
}

func (x *AcceptFriendRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// Ответ на принятие запроса на добавление в друзья
type AcceptFriendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // ACCEPTED в коде
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptFriendResponse) Reset() {
	*x = AcceptFriendResponse{}
	mi := &file_api_v1_social_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptFriendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptFriendResponse) ProtoMessage() {}

func (x *AcceptFriendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_social_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptFriendResponse.ProtoReflect.Descriptor instead.
func (*AcceptFriendResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_social_messages_proto_rawDescGZIP(), []int{6}
}

func (x *AcceptFriendResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AcceptFriendResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// Запрос на отклонение запроса на добавление в друзья
type DeclineFriendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeclineFriendRequest) Reset() {
	*x = DeclineFriendRequest{}
	mi := &file_api_v1_social_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeclineFriendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeclineFriendRequest) ProtoMessage() {}

func (x *DeclineFriendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_social_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeclineFriendRequest.ProtoReflect.Descriptor instead.
func (*DeclineFriendRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_social_messages_proto_rawDescGZIP(), []int{7}
}

func (x *DeclineFriendRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// Ответ на отклонение запроса на добавление в друзья
type DeclineFriendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // DECLINED в коде
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeclineFriendResponse) Reset() {
	*x = DeclineFriendResponse{}
	mi := &file_api_v1_social_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeclineFriendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeclineFriendResponse) ProtoMessage() {}

func (x *DeclineFriendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_social_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeclineFriendResponse.ProtoReflect.Descriptor instead.
func (*DeclineFriendResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_social_messages_proto_rawDescGZIP(), []int{8}
}

func (x *DeclineFriendResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *DeclineFriendResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// Запрос на удаление пользователя из друзей
type RemoveFriendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFriendRequest) Reset() {
	*x = RemoveFriendRequest{}
	mi := &file_api_v1_social_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFriendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFriendRequest) ProtoMessage() {}

func (x *RemoveFriendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_social_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFriendRequest.ProtoReflect.Descriptor instead.
func (*RemoveFriendRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_social_messages_proto_rawDescGZIP(), []int{9}
}

func (x *RemoveFriendRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Оттвет на удаление пользователя из друзей
type RemoveFriendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFriendResponse) Reset() {
	*x = RemoveFriendResponse{}
	mi := &file_api_v1_social_messages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFriendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFriendResponse) ProtoMessage() {}

func (x *RemoveFriendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_social_messages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFriendResponse.ProtoReflect.Descriptor instead.
func (*RemoveFriendResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_social_messages_proto_rawDescGZIP(), []int{10}
}

// Запрос на получение списка друзей
type ListFriendsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         uint32                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor        string                 `protobuf:"bytes,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFriendsRequest) Reset() {
	*x = ListFriendsRequest{}
	mi := &file_api_v1_social_messages_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFriendsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFriendsRequest) ProtoMessage() {}

func (x *ListFriendsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_social_messages_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFriendsRequest.ProtoReflect.Descriptor instead.
func (*ListFriendsRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_social_messages_proto_rawDescGZIP(), []int{11}
}

func (x *ListFriendsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListFriendsRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListFriendsRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

// Ответ на запрос на получение списка друзей
type ListFriendsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FriendUserIds []string               `protobuf:"bytes,1,rep,name=friend_user_ids,json=friendUserIds,proto3" json:"friend_user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFriendsResponse) Reset() {
	*x = ListFriendsResponse{}
	mi := &file_api_v1_social_messages_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFriendsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFriendsResponse) ProtoMessage() {}

func (x *ListFriendsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_social_messages_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFriendsResponse.ProtoReflect.Descriptor instead.
func (*ListFriendsResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_social_messages_proto_rawDescGZIP(), []int{12}
}

func (x *ListFriendsResponse) GetFriendUserIds() []string {
	if x != nil {
		return x.FriendUserIds
	}
	return nil
}

var File_api_v1_social_messages_proto protoreflect.FileDescriptor

const file_api_v1_social_messages_proto_rawDesc = "" +
	"\n" +
	"\x1capi/v1/social_messages.proto\x12'github.com.kheeva.mini_messenger.social\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"5\n" +
	"\x11SendFriendRequest\x12 \n" +
	"\auser_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06userId\"K\n" +
	"\x12SendFriendResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"7\n" +
	"\x13ListRequestsRequest\x12 \n" +
	"\auser_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06userId\"F\n" +
	"\rFriendRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"j\n" +
	"\x14ListRequestsResponse\x12R\n" +
	"\brequests\x18\x01 \x03(\v26.github.com.kheeva.mini_messenger.social.FriendRequestR\brequests\"4\n" +
	"\x13AcceptFriendRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\"M\n" +
	"\x14AcceptFriendResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"5\n" +
	"\x14DeclineFriendRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\"N\n" +
	"\x15DeclineFriendResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"7\n" +
	"\x13RemoveFriendRequest\x12 \n" +
	"\auser_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06userId\"\x16\n" +
	"\x14RemoveFriendResponse\"m\n" +
	"\x12ListFriendsRequest\x12 \n" +
	"\auser_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06userId\x12\x1d\n" +
	"\x05limit\x18\x02 \x01(\rB\a\xbaH\x04*\x02\x18dR\x05limit\x12\x16\n" +
	"\x06cursor\x18\x03 \x01(\tR\x06cursor\"=\n" +
	"\x13ListFriendsResponse\x12&\n" +
	"\x0ffriend_user_ids\x18\x01 \x03(\tR\rfriendUserIdsB\x93\x02\n" +
	"+com.github.com.kheeva.mini_messenger.socialB\x13SocialMessagesProtoP\x01Z\x11social/pkg;social\xa2\x02\x05GCKMS\xaa\x02&Github.Com.Kheeva.MiniMessenger.Social\xca\x02&Github\\Com\\Kheeva\\MiniMessenger\\Social\xe2\x022Github\\Com\\Kheeva\\MiniMessenger\\Social\\GPBMetadata\xea\x02*Github::Com::Kheeva::MiniMessenger::Socialb\x06proto3"

var (
	file_api_v1_social_messages_proto_rawDescOnce sync.Once
	file_api_v1_social_messages_proto_rawDescData []byte
)

func file_api_v1_social_messages_proto_rawDescGZIP() []byte {
	file_api_v1_social_messages_proto_rawDescOnce.Do(func() {
		file_api_v1_social_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_social_messages_proto_rawDesc), len(file_api_v1_social_messages_proto_rawDesc)))
	})
	return file_api_v1_social_messages_proto_rawDescData
}

var file_api_v1_social_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_v1_social_messages_proto_goTypes = []any{
	(*SendFriendRequest)(nil),     // 0: github.com.kheeva.mini_messenger.social.SendFriendRequest
	(*SendFriendResponse)(nil),    // 1: github.com.kheeva.mini_messenger.social.SendFriendResponse
	(*ListRequestsRequest)(nil),   // 2: github.com.kheeva.mini_messenger.social.ListRequestsRequest
	(*FriendRequest)(nil),         // 3: github.com.kheeva.mini_messenger.social.FriendRequest
	(*ListRequestsResponse)(nil),  // 4: github.com.kheeva.mini_messenger.social.ListRequestsResponse
	(*AcceptFriendRequest)(nil),   // 5: github.com.kheeva.mini_messenger.social.AcceptFriendRequest
	(*AcceptFriendResponse)(nil),  // 6: github.com.kheeva.mini_messenger.social.AcceptFriendResponse
	(*DeclineFriendRequest)(nil),  // 7: github.com.kheeva.mini_messenger.social.DeclineFriendRequest
	(*DeclineFriendResponse)(nil), // 8: github.com.kheeva.mini_messenger.social.DeclineFriendResponse
	(*RemoveFriendRequest)(nil),   // 9: github.com.kheeva.mini_messenger.social.RemoveFriendRequest
	(*RemoveFriendResponse)(nil),  // 10: github.com.kheeva.mini_messenger.social.RemoveFriendResponse
	(*ListFriendsRequest)(nil),    // 11: github.com.kheeva.mini_messenger.social.ListFriendsRequest
	(*ListFriendsResponse)(nil),   // 12: github.com.kheeva.mini_messenger.social.ListFriendsResponse
}
var file_api_v1_social_messages_proto_depIdxs = []int32{
	3, // 0: github.com.kheeva.mini_messenger.social.ListRequestsResponse.requests:type_name -> github.com.kheeva.mini_messenger.social.FriendRequest
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_v1_social_messages_proto_init() }
func file_api_v1_social_messages_proto_init() {
	if File_api_v1_social_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_social_messages_proto_rawDesc), len(file_api_v1_social_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_v1_social_messages_proto_goTypes,
		DependencyIndexes: file_api_v1_social_messages_proto_depIdxs,
		MessageInfos:      file_api_v1_social_messages_proto_msgTypes,
	}.Build()
	File_api_v1_social_messages_proto = out.File
	file_api_v1_social_messages_proto_goTypes = nil
	file_api_v1_social_messages_proto_depIdxs = nil
}
