// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: api/v1/social_service.proto

package social

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_v1_social_service_proto protoreflect.FileDescriptor

const file_api_v1_social_service_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/v1/social_service.proto\x12'github.com.kheeva.mini_messenger.social\x1a\x1capi/v1/social_messages.proto\x1a\x1cgoogle/api/annotations.proto2\x96\t\n" +
	"\rSocialService\x12\xaf\x01\n" +
	"\n" +
	"SendFriend\x12:.github.com.kheeva.mini_messenger.social.SendFriendRequest\x1a;.github.com.kheeva.mini_messenger.social.SendFriendResponse\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/api/social/v1/friend_request\x12\xc4\x01\n" +
	"\fListRequests\x12<.github.com.kheeva.mini_messenger.social.ListRequestsRequest\x1a=.github.com.kheeva.mini_messenger.social.ListRequestsResponse\"7\x82\xd3\xe4\x93\x021\x12//api/social/v1/friend_request/user_id/{user_id}\x12\xc9\x01\n" +
	"\fAcceptFriend\x12<.github.com.kheeva.mini_messenger.social.AcceptFriendRequest\x1a=.github.com.kheeva.mini_messenger.social.AcceptFriendResponse\"<\x82\xd3\xe4\x93\x026:\x01*\x1a1/api/social/v1/friend_request/accept/{request_id}\x12\xcd\x01\n" +
	"\rDeclineFriend\x12=.github.com.kheeva.mini_messenger.social.DeclineFriendRequest\x1a>.github.com.kheeva.mini_messenger.social.DeclineFriendResponse\"=\x82\xd3\xe4\x93\x027:\x01*\x1a2/api/social/v1/friend_request/decline/{request_id}\x12\xc4\x01\n" +
	"\fRemoveFriend\x12<.github.com.kheeva.mini_messenger.social.RemoveFriendRequest\x1a=.github.com.kheeva.mini_messenger.social.RemoveFriendResponse\"7\x82\xd3\xe4\x93\x021*//api/social/v1/friend_request/user_id/{user_id}\x12\xa8\x01\n" +
	"\vListFriends\x12;.github.com.kheeva.mini_messenger.social.ListFriendsRequest\x1a<.github.com.kheeva.mini_messenger.social.ListFriendsResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/api/social/v1/friendsB\x92\x02\n" +
	"+com.github.com.kheeva.mini_messenger.socialB\x12SocialServiceProtoP\x01Z\x11social/pkg;social\xa2\x02\x05GCKMS\xaa\x02&Github.Com.Kheeva.MiniMessenger.Social\xca\x02&Github\\Com\\Kheeva\\MiniMessenger\\Social\xe2\x022Github\\Com\\Kheeva\\MiniMessenger\\Social\\GPBMetadata\xea\x02*Github::Com::Kheeva::MiniMessenger::Socialb\x06proto3"

var file_api_v1_social_service_proto_goTypes = []any{
	(*SendFriendRequest)(nil),     // 0: github.com.kheeva.mini_messenger.social.SendFriendRequest
	(*ListRequestsRequest)(nil),   // 1: github.com.kheeva.mini_messenger.social.ListRequestsRequest
	(*AcceptFriendRequest)(nil),   // 2: github.com.kheeva.mini_messenger.social.AcceptFriendRequest
	(*DeclineFriendRequest)(nil),  // 3: github.com.kheeva.mini_messenger.social.DeclineFriendRequest
	(*RemoveFriendRequest)(nil),   // 4: github.com.kheeva.mini_messenger.social.RemoveFriendRequest
	(*ListFriendsRequest)(nil),    // 5: github.com.kheeva.mini_messenger.social.ListFriendsRequest
	(*SendFriendResponse)(nil),    // 6: github.com.kheeva.mini_messenger.social.SendFriendResponse
	(*ListRequestsResponse)(nil),  // 7: github.com.kheeva.mini_messenger.social.ListRequestsResponse
	(*AcceptFriendResponse)(nil),  // 8: github.com.kheeva.mini_messenger.social.AcceptFriendResponse
	(*DeclineFriendResponse)(nil), // 9: github.com.kheeva.mini_messenger.social.DeclineFriendResponse
	(*RemoveFriendResponse)(nil),  // 10: github.com.kheeva.mini_messenger.social.RemoveFriendResponse
	(*ListFriendsResponse)(nil),   // 11: github.com.kheeva.mini_messenger.social.ListFriendsResponse
}
var file_api_v1_social_service_proto_depIdxs = []int32{
	0,  // 0: github.com.kheeva.mini_messenger.social.SocialService.SendFriend:input_type -> github.com.kheeva.mini_messenger.social.SendFriendRequest
	1,  // 1: github.com.kheeva.mini_messenger.social.SocialService.ListRequests:input_type -> github.com.kheeva.mini_messenger.social.ListRequestsRequest
	2,  // 2: github.com.kheeva.mini_messenger.social.SocialService.AcceptFriend:input_type -> github.com.kheeva.mini_messenger.social.AcceptFriendRequest
	3,  // 3: github.com.kheeva.mini_messenger.social.SocialService.DeclineFriend:input_type -> github.com.kheeva.mini_messenger.social.DeclineFriendRequest
	4,  // 4: github.com.kheeva.mini_messenger.social.SocialService.RemoveFriend:input_type -> github.com.kheeva.mini_messenger.social.RemoveFriendRequest
	5,  // 5: github.com.kheeva.mini_messenger.social.SocialService.ListFriends:input_type -> github.com.kheeva.mini_messenger.social.ListFriendsRequest
	6,  // 6: github.com.kheeva.mini_messenger.social.SocialService.SendFriend:output_type -> github.com.kheeva.mini_messenger.social.SendFriendResponse
	7,  // 7: github.com.kheeva.mini_messenger.social.SocialService.ListRequests:output_type -> github.com.kheeva.mini_messenger.social.ListRequestsResponse
	8,  // 8: github.com.kheeva.mini_messenger.social.SocialService.AcceptFriend:output_type -> github.com.kheeva.mini_messenger.social.AcceptFriendResponse
	9,  // 9: github.com.kheeva.mini_messenger.social.SocialService.DeclineFriend:output_type -> github.com.kheeva.mini_messenger.social.DeclineFriendResponse
	10, // 10: github.com.kheeva.mini_messenger.social.SocialService.RemoveFriend:output_type -> github.com.kheeva.mini_messenger.social.RemoveFriendResponse
	11, // 11: github.com.kheeva.mini_messenger.social.SocialService.ListFriends:output_type -> github.com.kheeva.mini_messenger.social.ListFriendsResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_api_v1_social_service_proto_init() }
func file_api_v1_social_service_proto_init() {
	if File_api_v1_social_service_proto != nil {
		return
	}
	file_api_v1_social_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_social_service_proto_rawDesc), len(file_api_v1_social_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_social_service_proto_goTypes,
		DependencyIndexes: file_api_v1_social_service_proto_depIdxs,
	}.Build()
	File_api_v1_social_service_proto = out.File
	file_api_v1_social_service_proto_goTypes = nil
	file_api_v1_social_service_proto_depIdxs = nil
}
